/**
 * Training data statistics for feature standardisation.
 *
 * Auto-generated by csv_to_statistics_h.py
 * Timestamp  : 2026-02-27 20:26 UTC
 * Source     : lstm_data.csv
 * Mode       : by-plate-temperature (column 'plate_temperature')
 *
 * z-score normalisation applied per heater step:
 *
 *   z = (x - FEATURE_MEAN[step][i]) / FEATURE_STD[step][i]
 *
 * Features where FEATURE_STD[step][i] == 0.0 are passed through unchanged.
 * STATS_SEQ_LEN == 1 for forced-mode (single-step) models.
 *
 * Feature order — must match the order used when training the model:
 *   [0]  humidity                 ()
 *   [1]  gas_resistance           ()
 */

#ifndef STATISTICS_H
#define STATISTICS_H

constexpr int STATS_SEQ_LEN = 10;

// Feature Mean Array [Classes/Time-steps][Features]
static const float FEATURE_MEAN[8][1] = {
    {28.25871812f}, // Index 0 (Humidity Mean 1)
    {37.36478082f}, // Index 1
    {40.05958451f}, // Index 2
    {36.71642308f}, // Index 3
    {35.35853285f}, // Index 4
    {36.23986452f}, // Index 5
    {31.47810345f}, // Index 6
    {25.11798601f}  // Index 7
};

// Feature Standard Deviation Array [Classes/Time-steps][Features]
static const float FEATURE_STD[8][1] = {
    {3.79134537f}, {3.87945797f}, {6.94200623f}, {5.23985893f},
    {5.26721447f}, {4.95424315f}, {4.27913689f}, {4.10542819f}};

#endif /* STATISTICS_H */
