/**
 * Training data statistics for feature standardisation.
 *
 * Auto-generated by csv_to_statistics_h.py
 * Timestamp  : 2026-03-01 13:18 UTC
 * Source     : train_data.csv
 * Mode       : by-temp-profile (column 'plate_temperature', profile: 320 100 100 100 200 200 200 320 320 320)
 *
 * z-score normalisation applied per heater step:
 *
 *   z = (x - FEATURE_MEAN[step][i]) / FEATURE_STD[step][i]
 *
 * Features where FEATURE_STD[step][i] == 0.0 are passed through unchanged.
 * STATS_SEQ_LEN == 1 for forced-mode (single-step) models.
 *
 * Feature order — must match the order used when training the model:
 *   [0]  gas_resistance           ()
 *   [1]  gas_resistance_diff      ()
 */

#ifndef STATISTICS_H
#define STATISTICS_H

constexpr int STATS_SEQ_LEN = 10;

/* Per-step, per-feature mean  [heater_step][feature_index] */
const float FEATURE_MEAN[3][5] = {
    /* [320 °C] */
    {
        28.1f,
        1064.2f,
        43.6f,
        3191337.9f,
        -305737.8f,
    },
    /* [100 °C] */
    {
        28.1f,
        1064.2f,
        43.6f,
        3191337.9f,
        -305737.8f,
    },
    /* [100 °C] */
    {
        28.1f,
        1064.2f,
        43.6f,
        3191337.9f,
        -305737.8f,
    },
};

/* Per-step, per-feature std   [heater_step][feature_index]  (0.0 = pass-through) */
const float FEATURE_STD[3][5] = {
    /* [320 °C] */
    {
        2.6f,
        38.9f,
        7.3f,
        1978268.1f,
        323751.2f,
    },
    /* [100 °C] */
    {
        2.6f,
        38.9f,
        7.3f,
        1978268.1f,
        323751.2f,
    },
    /* [100 °C] */
    {
        2.6f,
        38.9f,
        7.3f,
        1978268.1f,
        323751.2f,
    },
};

#endif /* STATISTICS_H */
