/**
 * Training data statistics for feature standardisation.
 *
 * Auto-generated by csv_to_statistics_h.py
 * Timestamp  : 2026-03-03 01:58 UTC
 * Source     : train_data.csv
 * Mode       : by-temp-profile (column 'plate_temperature', profile: 320 100 100 100 200 200 200 320 320 320)
 *
 * z-score normalisation applied per heater step:
 *
 *   z = (x - FEATURE_MEAN[step][i]) / FEATURE_STD[step][i]
 *
 * Features where FEATURE_STD[step][i] == 0.0 are passed through unchanged.
 * STATS_SEQ_LEN == 1 for forced-mode (single-step) models.
 *
 * Feature order — must match the order used when training the model:
 *   [0]  gas_resistance           ()
 *   [1]  gas_resistance_diff      ()
 */

#ifndef STATISTICS_H
#define STATISTICS_H

constexpr int STATS_SEQ_LEN = 10;

/* Per-step, per-feature mean  [heater_step][feature_index] */
const float FEATURE_MEAN[10][2] = {
    /* [320 °C] */
    {
        -0.193994f,  // gas_resistance ()
        -0.299545f  // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        -0.248016f,  // gas_resistance ()
        -0.216321f  // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        -0.248016f,  // gas_resistance ()
        -0.216321f  // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        -0.248016f,  // gas_resistance ()
        -0.216321f  // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        -0.270151f,  // gas_resistance ()
        -0.35277f   // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        -0.270151f,  // gas_resistance ()
        -0.35277f   // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        -0.270151f,  // gas_resistance ()
        -0.35277f   // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        -0.193994f,  // gas_resistance ()
        -0.299545f  // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        -0.193994f,  // gas_resistance ()
        -0.299545f  // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        -0.193994f,  // gas_resistance ()
        -0.299545f  // gas_resistance_diff ()
    }
};

/* Per-step, per-feature std   [heater_step][feature_index]  (0.0 = pass-through) */
const float FEATURE_STD[10][2] = {
    /* [320 °C] */
    {
        0.261771f,  // gas_resistance ()
        0.664339f  // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        0.432989f,  // gas_resistance ()
        0.965019f  // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        0.432989f,  // gas_resistance ()
        0.965019f  // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        0.432989f,  // gas_resistance ()
        0.965019f  // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        0.356705f,  // gas_resistance ()
        0.570892f  // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        0.356705f,  // gas_resistance ()
        0.570892f  // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        0.356705f,  // gas_resistance ()
        0.570892f  // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        0.261771f,  // gas_resistance ()
        0.664339f  // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        0.261771f,  // gas_resistance ()
        0.664339f  // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        0.261771f,  // gas_resistance ()
        0.664339f  // gas_resistance_diff ()
    }
};

#endif /* STATISTICS_H */
