/**
 * Training data statistics for feature standardisation.
 *
 * Auto-generated by csv_to_statistics_h.py
 * Source : statistics.csv (BasicOils/custom_basic, n=6972)
 *
 * Used to z-score normalise each sensor reading before passing it to the
 * model:
 *
 *   z = (x - mean) / std      (features where std != 0.0)
 *
 * Features where std == 0.0 are passed through unchanged.
 *
 * Feature order — must match the order used when training the model:
 *   [0]  plate_temperature         (°C)   — pass-through
 *   [1]  heater_duration           (ms)   — pass-through
 *   [2]  temperature               (°C)
 *   [3]  pressure                  (hPa)
 *   [4]  humidity                  (%)
 *   [5]  gas_resistance            (Ω)
 */

#ifndef STATISTICS_H
#define STATISTICS_H

/* Per-feature mean of the training set */
const float FEATURE_MEAN[6] = {
    320.0f,           // plate_temperature         (°C)   — pass-through
    150.0f,           // heater_duration           (ms)   — pass-through
    31.8316f,         // temperature               (°C)
    1000.3915f,       // pressure                  (hPa)
    26.6163f,         // humidity                  (%)
    134856.3484f,     // gas_resistance            (Ω)
};

/* Per-feature standard deviation of the training set (0.0 = pass-through) */
const float FEATURE_STD[6] = {
    0.0f,             // plate_temperature         (°C)   — pass-through
    0.0f,             // heater_duration           (ms)   — pass-through
    1.1403f,          // temperature               (°C)
    1.5166f,          // pressure                  (hPa)
    2.1884f,          // humidity                  (%)
    74938.0426f,      // gas_resistance            (Ω)
};

#endif /* STATISTICS_H */
