/**
 * Training data statistics for feature standardisation.
 *
 * Auto-generated by csv_to_statistics_h.py
 * Timestamp  : 2026-02-27 20:26 UTC
 * Source     : lstm_data.csv
 * Mode       : by-plate-temperature (column 'plate_temperature')
 *
 * z-score normalisation applied per heater step:
 *
 *   z = (x - FEATURE_MEAN[step][i]) / FEATURE_STD[step][i]
 *
 * Features where FEATURE_STD[step][i] == 0.0 are passed through unchanged.
 * STATS_SEQ_LEN == 1 for forced-mode (single-step) models.
 *
 * Feature order — must match the order used when training the model:
 *   [0]  temperature              ()
 *   [1]  pressure                 ()
 *   [2]  humidity                 ()
 *   [3]  gas_resistance           ()
 */

#ifndef STATISTICS_H
#define STATISTICS_H

constexpr int STATS_SEQ_LEN = 10;

/* Per-step, per-feature mean  [heater_step][feature_index] */
const float FEATURE_MEAN[STATS_SEQ_LEN][8] = {
    /* [320 °C] */
    {
        26.08f,
        1065.74f,
        44.48f,
        67183.95f,
        0.02f,
        0.0f,
        -0.01f,
        -43262.77
    },
    /* [100 °C] */
    {
        26.08f,
        1065.74f,
        44.48f,
        4146099.06f,
        -0.01f,
        -0.0f,
        -0.02f,
        1192454.7
    },
    /* [100 °C] */
    {
        26.08f,
        1065.74f,
        44.48f,
        4146099.06f,
        -0.01f,
        -0.0f,
        -0.02f,
        1192454.7
    },
    /* [100 °C] */
    {
        26.08f,
        1065.74f,
        44.48f,
        4146099.06f,
        -0.01f,
        -0.0f,
        -0.02f,
        1192454.7
    },
    /* [200 °C] */
    {
        26.03f,
        1065.74f,
        44.48f,
        266532.21f,
        -0.01f,
        -0.0f,
        0.0f,
        -1135905.93
    },
    /* [200 °C] */
    {
        26.03f,
        1065.74f,
        44.48f,
        266532.21f,
        -0.01f,
        -0.0f,
        0.0f,
        -1135905.93
    },
    /* [200 °C] */
    {
        26.03f,
        1065.74f,
        44.48f,
        266532.21f,
        -0.01f,
        -0.0f,
        0.0f,
        -1135905.93
    },
    /* [320 °C] */
    {
        26.08f,
        1065.74f,
        44.48f,
        67183.95f,
        0.02f,
        0.0f,
        -0.01f,
        -43262.77
    },
    /* [320 °C] */
    {
        26.08f,
        1065.74f,
        44.48f,
        67183.95f,
        0.02f,
        0.0f,
        -0.01f,
        -43262.77
    },
    /* [320 °C] */
    {
        26.08f,
        1065.74f,
        44.48f,
        67183.95f,
        0.02f,
        0.0f,
        -0.01f,
        -43262.77
    },
};

/* Per-step, per-feature std   [heater_step][feature_index]  (0.0 = pass-through) */
const float FEATURE_STD[STATS_SEQ_LEN][8] = {
    /* [320 °C] */
    {
        4.79f,
        38.66f,
        7.14f,
        29589.33f,
        0.01f,
        0.01f,
        0.09f,
        110646.94
    },
    /* [100 °C] */
    {
        4.79f,
        38.66f,
        7.18f,
        2977612.35f,
        0.02f,
        0.01f,
        0.1f,
        3113207.07
    },
    /* [100 °C] */
    {
        4.79f,
        38.66f,
        7.18f,
        2977612.35f,
        0.02f,
        0.01f,
        0.1f,
        3113207.07
    },
    /* [100 °C] */
    {
        4.79f,
        38.66f,
        7.18f,
        2977612.35f,
        0.02f,
        0.01f,
        0.1f,
        3113207.07
    },
    /* [200 °C] */
    {
        4.79f,
        38.65f,
        7.15f,
        184049.12f,
        0.02f,
        0.01f,
        0.1f,
        2118962.09
    },
    /* [200 °C] */
    {
        4.79f,
        38.65f,
        7.15f,
        184049.12f,
        0.02f,
        0.01f,
        0.1f,
        2118962.09
    },
    /* [200 °C] */
    {
        4.79f,
        38.65f,
        7.15f,
        184049.12f,
        0.02f,
        0.01f,
        0.1f,
        2118962.09
    },
    /* [320 °C] */
    {
        4.79f,
        38.66f,
        7.14f,
        29589.33f,
        0.01f,
        0.01f,
        0.09f,
        110646.94
    },
    /* [320 °C] */
    {
        4.79f,
        38.66f,
        7.14f,
        29589.33f,
        0.01f,
        0.01f,
        0.09f,
        110646.94
    },
    /* [320 °C] */
    {
        4.79f,
        38.66f,
        7.14f,
        29589.33f,
        0.01f,
        0.01f,
        0.09f,
        110646.94
    },
};

#endif /* STATISTICS_H */
