/**
 * Training data statistics for feature standardisation.
 *
 * Auto-generated by csv_to_statistics_h.py
 * Timestamp  : 2026-02-27 20:26 UTC
 * Source     : lstm_data.csv
 * Mode       : by-plate-temperature (column 'plate_temperature')
 *
 * z-score normalisation applied per heater step:
 *
 *   z = (x - FEATURE_MEAN[step][i]) / FEATURE_STD[step][i]
 *
 * Features where FEATURE_STD[step][i] == 0.0 are passed through unchanged.
 * STATS_SEQ_LEN == 1 for forced-mode (single-step) models.
 *
 * Feature order — must match the order used when training the model:
 *   [0]  temperature              ()
 *   [1]  pressure                 ()
 *   [2]  humidity                 ()
 *   [3]  gas_resistance           ()
 */

#ifndef STATISTICS_H
#define STATISTICS_H

constexpr int STATS_SEQ_LEN = 10;

/* Per-step, per-feature mean  [heater_step][feature_index] */
const float FEATURE_MEAN[STATS_SEQ_LEN][4] = {
    /* [320 °C] */
    {
        28.3167f,  // temperature ()
        1062.73f,  // pressure ()
        44.601f,   // humidity ()
        53425.4f  // gas_resistance ()
    },
    /* [100 °C] */
    {
        28.3311f,      // temperature ()
        1062.9f,       // pressure ()
        44.6094f,      // humidity ()
        2.83375e+06f  // gas_resistance ()
    },
    /* [100 °C] */
    {
        28.3311f,      // temperature ()
        1062.9f,       // pressure ()
        44.6094f,      // humidity ()
        2.83375e+06f  // gas_resistance ()
    },
    /* [100 °C] */
    {
        28.3311f,      // temperature ()
        1062.9f,       // pressure ()
        44.6094f,      // humidity ()
        2.83375e+06f  // gas_resistance ()
    },
    /* [200 °C] */
    {
        28.2576f,   // temperature ()
        1062.8f,    // pressure ()
        44.6358f,   // humidity ()
        174560.0f  // gas_resistance ()
    },
    /* [200 °C] */
    {
        28.2576f,   // temperature ()
        1062.8f,    // pressure ()
        44.6358f,   // humidity ()
        174560.0f  // gas_resistance ()
    },
    /* [200 °C] */
    {
        28.2576f,   // temperature ()
        1062.8f,    // pressure ()
        44.6358f,   // humidity ()
        174560.0f  // gas_resistance ()
    },
    /* [320 °C] */
    {
        28.3167f,  // temperature ()
        1062.73f,  // pressure ()
        44.601f,   // humidity ()
        53425.4f  // gas_resistance ()
    },
    /* [320 °C] */
    {
        28.3167f,  // temperature ()
        1062.73f,  // pressure ()
        44.601f,   // humidity ()
        53425.4f  // gas_resistance ()
    },
    /* [320 °C] */
    {
        28.3167f,  // temperature ()
        1062.73f,  // pressure ()
        44.601f,   // humidity ()
        53425.4f  // gas_resistance ()
    },
};

/* Per-step, per-feature std   [heater_step][feature_index]  (0.0 = pass-through) */
const float FEATURE_STD[STATS_SEQ_LEN][4] = {
    /* [320 °C] */
    {
        2.70542f,  // temperature ()
        38.8032f,  // pressure ()
        7.32655f,  // humidity ()
        20950.9f  // gas_resistance ()
    },
    /* [100 °C] */
    {
        2.72169f,      // temperature ()
        38.754f,       // pressure ()
        7.34288f,      // humidity ()
        1.95615e+06f  // gas_resistance ()
    },
    /* [100 °C] */
    {
        2.72169f,      // temperature ()
        38.754f,       // pressure ()
        7.34288f,      // humidity ()
        1.95615e+06f  // gas_resistance ()
    },
    /* [100 °C] */
    {
        2.72169f,      // temperature ()
        38.754f,       // pressure ()
        7.34288f,      // humidity ()
        1.95615e+06f  // gas_resistance ()
    },
    /* [200 °C] */
    {
        2.71093f,   // temperature ()
        38.7733f,   // pressure ()
        7.34303f,   // humidity ()
        111926.0f  // gas_resistance ()
    },
    /* [200 °C] */
    {
        2.71093f,   // temperature ()
        38.7733f,   // pressure ()
        7.34303f,   // humidity ()
        111926.0f  // gas_resistance ()
    },
    /* [200 °C] */
    {
        2.71093f,   // temperature ()
        38.7733f,   // pressure ()
        7.34303f,   // humidity ()
        111926.0f  // gas_resistance ()
    },
    /* [320 °C] */
    {
        2.70542f,  // temperature ()
        38.8032f,  // pressure ()
        7.32655f,  // humidity ()
        20950.9f  // gas_resistance ()
    },
    /* [320 °C] */
    {
        2.70542f,  // temperature ()
        38.8032f,  // pressure ()
        7.32655f,  // humidity ()
        20950.9f  // gas_resistance ()
    },
    /* [320 °C] */
    {
        2.70542f,  // temperature ()
        38.8032f,  // pressure ()
        7.32655f,  // humidity ()
        20950.9f  // gas_resistance ()
    },
};

#endif /* STATISTICS_H */
