/**
 * Training data statistics for feature standardisation.
 *
 * Auto-generated by csv_to_statistics_h.py
 * Timestamp  : 2026-03-03 11:38 UTC
 * Source     : train_data.csv
 * Mode       : by-position (column 'position')
 *
 * z-score normalisation applied per heater step:
 *
 *   z = (x - FEATURE_MEAN[step][i]) / FEATURE_STD[step][i]
 *
 * Features where FEATURE_STD[step][i] == 0.0 are passed through unchanged.
 * STATS_SEQ_LEN == 1 for forced-mode (single-step) models.
 *
 * Feature order — must match the order used when training the model:
 *   [0]  humidity                 ()
 *   [1]  humidity_diff            ()
 *   [2]  gas_resistance           ()
 *   [3]  gas_resistance_diff      ()
 */

#ifndef STATISTICS_H
#define STATISTICS_H

constexpr int STATS_SEQ_LEN = 10;

/* Per-step, per-feature mean  [heater_step][feature_index] */
const float FEATURE_MEAN[10][4] = {
    /* [step 0] */
    {
        0.0171941f,  // humidity ()
        0.0f,        // humidity_diff ()
        -0.106711f,  // gas_resistance ()
        0.0f        // gas_resistance_diff ()
    },
    /* [step 1] */
    {
        0.017351f,   // humidity ()
        -0.185929f,  // humidity_diff ()
        -0.149962f,  // gas_resistance ()
        -0.150695f  // gas_resistance_diff ()
    },
    /* [step 2] */
    {
        0.017494f,   // humidity ()
        -0.189121f,  // humidity_diff ()
        -0.114797f,  // gas_resistance ()
        -0.235836f  // gas_resistance_diff ()
    },
    /* [step 3] */
    {
        0.0179196f,   // humidity ()
        -0.427884f,   // humidity_diff ()
        -0.0880673f,  // gas_resistance ()
        -0.218f      // gas_resistance_diff ()
    },
    /* [step 4] */
    {
        0.017973f,    // humidity ()
        -0.684582f,   // humidity_diff ()
        -0.139442f,   // gas_resistance ()
        -0.0819261f  // gas_resistance_diff ()
    },
    /* [step 5] */
    {
        0.0183264f,  // humidity ()
        -1.03313f,   // humidity_diff ()
        -0.167903f,  // gas_resistance ()
        0.181481f   // gas_resistance_diff ()
    },
    /* [step 6] */
    {
        0.0184454f,  // humidity ()
        -0.248152f,  // humidity_diff ()
        -0.183806f,  // gas_resistance ()
        0.0507022f  // gas_resistance_diff ()
    },
    /* [step 7] */
    {
        0.0185547f,   // humidity ()
        -0.981383f,   // humidity_diff ()
        -0.0997231f,  // gas_resistance ()
        -0.228775f   // gas_resistance_diff ()
    },
    /* [step 8] */
    {
        0.0185097f,  // humidity ()
        0.370071f,   // humidity_diff ()
        -0.10811f,   // gas_resistance ()
        -0.154352f  // gas_resistance_diff ()
    },
    /* [step 9] */
    {
        0.0185966f,  // humidity ()
        -0.420585f,  // humidity_diff ()
        -0.117004f,  // gas_resistance ()
        -0.208168f  // gas_resistance_diff ()
    }
};

/* Per-step, per-feature std   [heater_step][feature_index]  (0.0 = pass-through) */
const float FEATURE_STD[10][4] = {
    /* [step 0] */
    {
        0.0276848f,  // humidity ()
        0.0f,        // humidity_diff ()
        0.225009f,   // gas_resistance ()
        0.0f        // gas_resistance_diff ()
    },
    /* [step 1] */
    {
        0.0277118f,  // humidity ()
        1.63816f,    // humidity_diff ()
        0.340604f,   // gas_resistance ()
        0.342926f   // gas_resistance_diff ()
    },
    /* [step 2] */
    {
        0.028091f,  // humidity ()
        2.62081f,   // humidity_diff ()
        0.34681f,   // gas_resistance ()
        0.365364f  // gas_resistance_diff ()
    },
    /* [step 3] */
    {
        0.0275945f,  // humidity ()
        7.39299f,    // humidity_diff ()
        0.350102f,   // gas_resistance ()
        0.375928f   // gas_resistance_diff ()
    },
    /* [step 4] */
    {
        0.0280521f,  // humidity ()
        2.99765f,    // humidity_diff ()
        0.267754f,   // gas_resistance ()
        0.359714f   // gas_resistance_diff ()
    },
    /* [step 5] */
    {
        0.0277979f,  // humidity ()
        4.67905f,    // humidity_diff ()
        0.269149f,   // gas_resistance ()
        0.464411f   // gas_resistance_diff ()
    },
    /* [step 6] */
    {
        0.02766f,   // humidity ()
        5.06353f,   // humidity_diff ()
        0.269796f,  // gas_resistance ()
        0.391275f  // gas_resistance_diff ()
    },
    /* [step 7] */
    {
        0.0278396f,  // humidity ()
        29.2832f,    // humidity_diff ()
        0.203551f,   // gas_resistance ()
        0.308658f   // gas_resistance_diff ()
    },
    /* [step 8] */
    {
        0.0273572f,  // humidity ()
        5.59298f,    // humidity_diff ()
        0.204058f,   // gas_resistance ()
        0.225978f   // gas_resistance_diff ()
    },
    /* [step 9] */
    {
        0.0272656f,  // humidity ()
        7.30096f,    // humidity_diff ()
        0.20416f,    // gas_resistance ()
        0.245388f   // gas_resistance_diff ()
    }
};

#endif /* STATISTICS_H */
