/**
 * Training data statistics for feature standardisation.
 *
 * Auto-generated by csv_to_statistics_h.py
 * Timestamp  : 2026-03-01 11:54 UTC
 * Source     : cnn_data.csv
 * Mode       : by-temp-profile (column 'plate_temperature', profile: 320 100 100 100 200 200 200 320 320 320)
 *
 * z-score normalisation applied per heater step:
 *
 *   z = (x - FEATURE_MEAN[step][i]) / FEATURE_STD[step][i]
 *
 * Features where FEATURE_STD[step][i] == 0.0 are passed through unchanged.
 * STATS_SEQ_LEN == 1 for forced-mode (single-step) models.
 *
 * Feature order — must match the order used when training the model:
 *   [0]  temperature              ()
 *   [1]  pressure                 ()
 *   [2]  humidity                 ()
 *   [3]  gas_resistance           ()
 *   [4]  temperature_diff         ()
 *   [5]  pressure_diff            ()
 *   [6]  humidity_diff            ()
 *   [7]  gas_resistance_diff      ()
 */

#ifndef STATISTICS_H
#define STATISTICS_H

constexpr int STATS_SEQ_LEN = 10;

/* Per-step, per-feature mean  [heater_step][feature_index] */
const float FEATURE_MEAN[10][8] = {
    /* [320 °C] */
    {
        26.077f,       // temperature ()
        1065.74f,      // pressure ()
        44.4803f,      // humidity ()
        67184.0f,      // gas_resistance ()
        0.0154684f,    // temperature_diff ()
        0.000768601f,  // pressure_diff ()
        -0.00917225f,  // humidity_diff ()
        -43262.8f     // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        26.0844f,       // temperature ()
        1065.74f,       // pressure ()
        44.4838f,       // humidity ()
        4.1461e+06f,    // gas_resistance ()
        -0.00844692f,   // temperature_diff ()
        -0.000491567f,  // pressure_diff ()
        -0.0231746f,    // humidity_diff ()
        1.19245e+06f   // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        26.0844f,       // temperature ()
        1065.74f,       // pressure ()
        44.4838f,       // humidity ()
        4.1461e+06f,    // gas_resistance ()
        -0.00844692f,   // temperature_diff ()
        -0.000491567f,  // pressure_diff ()
        -0.0231746f,    // humidity_diff ()
        1.19245e+06f   // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        26.0844f,       // temperature ()
        1065.74f,       // pressure ()
        44.4838f,       // humidity ()
        4.1461e+06f,    // gas_resistance ()
        -0.00844692f,   // temperature_diff ()
        -0.000491567f,  // pressure_diff ()
        -0.0231746f,    // humidity_diff ()
        1.19245e+06f   // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        26.0345f,       // temperature ()
        1065.74f,       // pressure ()
        44.4787f,       // humidity ()
        266532.0f,      // gas_resistance ()
        -0.00644643f,   // temperature_diff ()
        -0.000269345f,  // pressure_diff ()
        0.00458036f,    // humidity_diff ()
        -1.13591e+06f  // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        26.0345f,       // temperature ()
        1065.74f,       // pressure ()
        44.4787f,       // humidity ()
        266532.0f,      // gas_resistance ()
        -0.00644643f,   // temperature_diff ()
        -0.000269345f,  // pressure_diff ()
        0.00458036f,    // humidity_diff ()
        -1.13591e+06f  // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        26.0345f,       // temperature ()
        1065.74f,       // pressure ()
        44.4787f,       // humidity ()
        266532.0f,      // gas_resistance ()
        -0.00644643f,   // temperature_diff ()
        -0.000269345f,  // pressure_diff ()
        0.00458036f,    // humidity_diff ()
        -1.13591e+06f  // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        26.077f,       // temperature ()
        1065.74f,      // pressure ()
        44.4803f,      // humidity ()
        67184.0f,      // gas_resistance ()
        0.0154684f,    // temperature_diff ()
        0.000768601f,  // pressure_diff ()
        -0.00917225f,  // humidity_diff ()
        -43262.8f     // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        26.077f,       // temperature ()
        1065.74f,      // pressure ()
        44.4803f,      // humidity ()
        67184.0f,      // gas_resistance ()
        0.0154684f,    // temperature_diff ()
        0.000768601f,  // pressure_diff ()
        -0.00917225f,  // humidity_diff ()
        -43262.8f     // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        26.077f,       // temperature ()
        1065.74f,      // pressure ()
        44.4803f,      // humidity ()
        67184.0f,      // gas_resistance ()
        0.0154684f,    // temperature_diff ()
        0.000768601f,  // pressure_diff ()
        -0.00917225f,  // humidity_diff ()
        -43262.8f     // gas_resistance_diff ()
    }
};

/* Per-step, per-feature std   [heater_step][feature_index]  (0.0 = pass-through) */
const float FEATURE_STD[10][8] = {
    /* [320 °C] */
    {
        4.79318f,     // temperature ()
        38.6553f,     // pressure ()
        7.14264f,     // humidity ()
        29589.3f,     // gas_resistance ()
        0.0139793f,   // temperature_diff ()
        0.00591154f,  // pressure_diff ()
        0.0851153f,   // humidity_diff ()
        110647.0f    // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        4.78871f,      // temperature ()
        38.6558f,      // pressure ()
        7.17734f,      // humidity ()
        2.97761e+06f,  // gas_resistance ()
        0.024726f,     // temperature_diff ()
        0.00691099f,   // pressure_diff ()
        0.0994713f,    // humidity_diff ()
        3.11321e+06f  // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        4.78871f,      // temperature ()
        38.6558f,      // pressure ()
        7.17734f,      // humidity ()
        2.97761e+06f,  // gas_resistance ()
        0.024726f,     // temperature_diff ()
        0.00691099f,   // pressure_diff ()
        0.0994713f,    // humidity_diff ()
        3.11321e+06f  // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        4.78871f,      // temperature ()
        38.6558f,      // pressure ()
        7.17734f,      // humidity ()
        2.97761e+06f,  // gas_resistance ()
        0.024726f,     // temperature_diff ()
        0.00691099f,   // pressure_diff ()
        0.0994713f,    // humidity_diff ()
        3.11321e+06f  // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        4.78991f,      // temperature ()
        38.6549f,      // pressure ()
        7.14755f,      // humidity ()
        184049.0f,     // gas_resistance ()
        0.0177428f,    // temperature_diff ()
        0.00677986f,   // pressure_diff ()
        0.0990602f,    // humidity_diff ()
        2.11896e+06f  // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        4.78991f,      // temperature ()
        38.6549f,      // pressure ()
        7.14755f,      // humidity ()
        184049.0f,     // gas_resistance ()
        0.0177428f,    // temperature_diff ()
        0.00677986f,   // pressure_diff ()
        0.0990602f,    // humidity_diff ()
        2.11896e+06f  // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        4.78991f,      // temperature ()
        38.6549f,      // pressure ()
        7.14755f,      // humidity ()
        184049.0f,     // gas_resistance ()
        0.0177428f,    // temperature_diff ()
        0.00677986f,   // pressure_diff ()
        0.0990602f,    // humidity_diff ()
        2.11896e+06f  // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        4.79318f,     // temperature ()
        38.6553f,     // pressure ()
        7.14264f,     // humidity ()
        29589.3f,     // gas_resistance ()
        0.0139793f,   // temperature_diff ()
        0.00591154f,  // pressure_diff ()
        0.0851153f,   // humidity_diff ()
        110647.0f    // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        4.79318f,     // temperature ()
        38.6553f,     // pressure ()
        7.14264f,     // humidity ()
        29589.3f,     // gas_resistance ()
        0.0139793f,   // temperature_diff ()
        0.00591154f,  // pressure_diff ()
        0.0851153f,   // humidity_diff ()
        110647.0f    // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        4.79318f,     // temperature ()
        38.6553f,     // pressure ()
        7.14264f,     // humidity ()
        29589.3f,     // gas_resistance ()
        0.0139793f,   // temperature_diff ()
        0.00591154f,  // pressure_diff ()
        0.0851153f,   // humidity_diff ()
        110647.0f    // gas_resistance_diff ()
    }
};

#endif /* STATISTICS_H */
