/**
 * Training data statistics for feature standardisation.
 *
 * Auto-generated by csv_to_statistics_h.py
 * Timestamp  : 2026-03-03 11:09 UTC
 * Source     : train_data.csv
 * Mode       : by-position (column 'position')
 *
 * z-score normalisation applied per heater step:
 *
 *   z = (x - FEATURE_MEAN[step][i]) / FEATURE_STD[step][i]
 *
 * Features where FEATURE_STD[step][i] == 0.0 are passed through unchanged.
 * STATS_SEQ_LEN == 1 for forced-mode (single-step) models.
 *
 * Feature order — must match the order used when training the model:
 *   [0]  temperature              ()
 *   [1]  temperature_diff         ()
 *   [2]  humidity                 ()
 *   [3]  humidity_diff            ()
 *   [4]  pressure                 ()
 *   [5]  pressure_diff            ()
 *   [6]  gas_resistance           ()
 *   [7]  gas_resistance_diff      ()
 */

#ifndef STATISTICS_H
#define STATISTICS_H

constexpr int STATS_SEQ_LEN = 10;

/* Per-step, per-feature mean  [heater_step][feature_index] */
const float FEATURE_MEAN[10][8] = {
    /* [step 0] */
    {
        0.0120541f,    // temperature ()
        0.000158023f,  // pressure ()
        0.0359165f,    // humidity ()
        -0.18863f,     // gas_resistance ()
        0.0f,          // temperature_diff ()
        0.0f,          // pressure_diff ()
        0.0f,          // humidity_diff ()
        0.0f          // gas_resistance_diff ()
    },
    /* [step 1] */
    {
        0.0120308f,    // temperature ()
        0.000158532f,  // pressure ()
        0.0361057f,    // humidity ()
        -0.275684f,    // gas_resistance ()
        -0.00436077f,  // temperature_diff ()
        -0.683271f,    // pressure_diff ()
        -0.203919f,    // humidity_diff ()
        -0.277055f    // gas_resistance_diff ()
    },
    /* [step 2] */
    {
        0.0120663f,    // temperature ()
        0.000160516f,  // pressure ()
        0.0363097f,    // humidity ()
        -0.254774f,    // gas_resistance ()
        -0.0373624f,   // temperature_diff ()
        -0.866429f,    // pressure_diff ()
        -0.13021f,     // humidity_diff ()
        -0.315787f    // gas_resistance_diff ()
    },
    /* [step 3] */
    {
        0.0120992f,   // temperature ()
        0.00016104f,  // pressure ()
        0.0365868f,   // humidity ()
        -0.238463f,   // gas_resistance ()
        -0.0195122f,  // temperature_diff ()
        -280.736f,    // pressure_diff ()
        -0.783057f,   // humidity_diff ()
        -0.309755f   // gas_resistance_diff ()
    },
    /* [step 4] */
    {
        0.0121016f,    // temperature ()
        0.000161854f,  // pressure ()
        0.036619f,     // humidity ()
        -0.257819f,    // gas_resistance ()
        0.0181082f,    // temperature_diff ()
        93.073f,       // pressure_diff ()
        -0.650986f,    // humidity_diff ()
        -0.235511f    // gas_resistance_diff ()
    },
    /* [step 5] */
    {
        0.0121116f,    // temperature ()
        0.000162858f,  // pressure ()
        0.0367031f,    // humidity ()
        -0.278016f,    // gas_resistance ()
        0.677203f,     // temperature_diff ()
        653.107f,      // pressure_diff ()
        -0.980387f,    // humidity_diff ()
        -0.0274763f   // gas_resistance_diff ()
    },
    /* [step 6] */
    {
        0.0121072f,   // temperature ()
        0.00016486f,  // pressure ()
        0.0368065f,   // humidity ()
        -0.289162f,   // gas_resistance ()
        0.0138346f,   // temperature_diff ()
        0.473001f,    // pressure_diff ()
        -0.225395f,   // humidity_diff ()
        -0.122921f   // gas_resistance_diff ()
    },
    /* [step 7] */
    {
        0.0121067f,    // temperature ()
        0.000165312f,  // pressure ()
        0.0368932f,    // humidity ()
        -0.189859f,    // gas_resistance ()
        0.0323167f,    // temperature_diff ()
        0.529068f,     // pressure_diff ()
        -0.883788f,    // humidity_diff ()
        -0.3346f      // gas_resistance_diff ()
    },
    /* [step 8] */
    {
        0.0121152f,    // temperature ()
        0.000166131f,  // pressure ()
        0.0366966f,    // humidity ()
        -0.190712f,    // gas_resistance ()
        0.0275406f,    // temperature_diff ()
        653.697f,      // pressure_diff ()
        0.11836f,      // humidity_diff ()
        -0.191869f    // gas_resistance_diff ()
    },
    /* [step 9] */
    {
        0.0120913f,    // temperature ()
        0.000168122f,  // pressure ()
        0.0369702f,    // humidity ()
        -0.193504f,    // gas_resistance ()
        -0.00765817f,  // temperature_diff ()
        0.0900069f,    // pressure_diff ()
        -0.0166285f,   // humidity_diff ()
        -0.218415f    // gas_resistance_diff ()
    }
};

/* Per-step, per-feature std   [heater_step][feature_index]  (0.0 = pass-through) */
const float FEATURE_STD[10][8] = {
    /* [step 0] */
    {
        0.0218887f,    // temperature ()
        0.000222059f,  // pressure ()
        0.0436515f,    // humidity ()
        0.286926f,     // gas_resistance ()
        0.0f,          // temperature_diff ()
        0.0f,          // pressure_diff ()
        0.0f,          // humidity_diff ()
        0.0f          // gas_resistance_diff ()
    },
    /* [step 1] */
    {
        0.0215825f,    // temperature ()
        0.000221864f,  // pressure ()
        0.0437124f,    // humidity ()
        0.414577f,     // gas_resistance ()
        0.429761f,     // temperature_diff ()
        3.78949f,      // pressure_diff ()
        1.73876f,      // humidity_diff ()
        0.416937f     // gas_resistance_diff ()
    },
    /* [step 2] */
    {
        0.0212786f,    // temperature ()
        0.000224053f,  // pressure ()
        0.0441409f,    // humidity ()
        0.431619f,     // gas_resistance ()
        0.797347f,     // temperature_diff ()
        3.18259f,      // pressure_diff ()
        2.28539f,      // humidity_diff ()
        0.396385f     // gas_resistance_diff ()
    },
    /* [step 3] */
    {
        0.0210255f,    // temperature ()
        0.000225497f,  // pressure ()
        0.043609f,     // humidity ()
        0.442482f,     // gas_resistance ()
        0.485788f,     // temperature_diff ()
        3751.19f,      // pressure_diff ()
        8.62319f,      // humidity_diff ()
        0.413793f     // gas_resistance_diff ()
    },
    /* [step 4] */
    {
        0.0207502f,    // temperature ()
        0.000226698f,  // pressure ()
        0.0437457f,    // humidity ()
        0.356542f,     // gas_resistance ()
        0.507814f,     // temperature_diff ()
        2568.1f,       // pressure_diff ()
        4.67681f,      // humidity_diff ()
        0.451841f     // gas_resistance_diff ()
    },
    /* [step 5] */
    {
        0.0205182f,    // temperature ()
        0.000228343f,  // pressure ()
        0.0431968f,    // humidity ()
        0.348775f,     // gas_resistance ()
        5.88545f,      // temperature_diff ()
        3950.6f,       // pressure_diff ()
        4.82168f,      // humidity_diff ()
        0.579543f     // gas_resistance_diff ()
    },
    /* [step 6] */
    {
        0.020312f,     // temperature ()
        0.000229843f,  // pressure ()
        0.0431772f,    // humidity ()
        0.343931f,     // gas_resistance ()
        0.85337f,      // temperature_diff ()
        6.23637f,      // pressure_diff ()
        12.524f,       // humidity_diff ()
        0.502595f     // gas_resistance_diff ()
    },
    /* [step 7] */
    {
        0.0201138f,    // temperature ()
        0.000231247f,  // pressure ()
        0.0431826f,    // humidity ()
        0.276973f,     // gas_resistance ()
        0.700563f,     // temperature_diff ()
        4.29494f,      // pressure_diff ()
        26.9265f,      // humidity_diff ()
        0.374586f     // gas_resistance_diff ()
    },
    /* [step 8] */
    {
        0.0199418f,    // temperature ()
        0.000231512f,  // pressure ()
        0.0427098f,    // humidity ()
        0.26814f,      // gas_resistance ()
        0.277123f,     // temperature_diff ()
        4.42738f,      // humidity_diff ()
        3704.0f,       // pressure_diff ()
        0.235749f     // gas_resistance_diff ()
    },
    /* [step 9] */
    {
        0.0197611f,    // temperature ()
        0.000234305f,  // pressure ()
        0.0428656f,    // humidity ()
        0.260248f,     // gas_resistance ()
        0.221655f,     // temperature_diff ()
        9.33028f,      // pressure_diff ()
        13.9369f,      // humidity_diff ()
        0.22628f      // gas_resistance_diff ()
    }
};

#endif /* STATISTICS_H */
