/**
 * Training data statistics for feature standardisation.
 *
 * Auto-generated by csv_to_statistics_h.py
 * Timestamp  : 2026-03-02 10:51 UTC
 * Source     : train_data.csv
 * Mode       : by-temp-profile (column 'plate_temperature', profile: 320 100 100 100 200 200 200 320 320 320)
 *
 * z-score normalisation applied per heater step:
 *
 *   z = (x - FEATURE_MEAN[step][i]) / FEATURE_STD[step][i]
 *
 * Features where FEATURE_STD[step][i] == 0.0 are passed through unchanged.
 * STATS_SEQ_LEN == 1 for forced-mode (single-step) models.
 *
 * Feature order — must match the order used when training the model:
 *   [0]  temperature              ()
 *   [1]  temperature_diff         ()
 *   [2]  humidity                 ()
 *   [3]  humidity_diff            ()
 *   [4]  pressure                 ()
 *   [5]  pressure_diff            ()
 *   [6]  gas_resistance           ()
 *   [7]  gas_resistance_diff      ()
 */

#ifndef STATISTICS_H
#define STATISTICS_H

constexpr int STATS_SEQ_LEN = 10;

/* Per-step, per-feature mean  [heater_step][feature_index] */
const float FEATURE_MEAN[10][8] = {
    /* [320 °C] */
    {
        0.105493f,      // temperature ()
        -0.100359f,     // temperature_diff ()
        -0.123939f,     // humidity ()
        -0.354843f,     // humidity_diff ()
        -0.000865567f,  // pressure ()
        -0.096866f,     // pressure_diff ()
        -0.041709f,     // gas_resistance ()
        -0.309593f     // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        0.106723f,      // temperature ()
        0.556581f,      // temperature_diff ()
        -0.124815f,     // humidity ()
        -0.317303f,     // humidity_diff ()
        -0.000608226f,  // pressure ()
        0.380635f,      // pressure_diff ()
        -0.0229503f,    // gas_resistance ()
        -0.132925f     // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        0.106723f,      // temperature ()
        0.556581f,      // temperature_diff ()
        -0.124815f,     // humidity ()
        -0.317303f,     // humidity_diff ()
        -0.000608226f,  // pressure ()
        0.380635f,      // pressure_diff ()
        -0.0229503f,    // gas_resistance ()
        -0.132925f     // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        0.106723f,      // temperature ()
        0.556581f,      // temperature_diff ()
        -0.124815f,     // humidity ()
        -0.317303f,     // humidity_diff ()
        -0.000608226f,  // pressure ()
        0.380635f,      // pressure_diff ()
        -0.0229503f,    // gas_resistance ()
        -0.132925f     // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        0.107383f,      // temperature ()
        0.342512f,      // temperature_diff ()
        -0.125204f,     // humidity ()
        1.18193f,       // humidity_diff ()
        -0.000639384f,  // pressure ()
        -0.298502f,     // pressure_diff ()
        -0.210775f,     // gas_resistance ()
        -0.087954f     // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        0.107383f,      // temperature ()
        0.342512f,      // temperature_diff ()
        -0.125204f,     // humidity ()
        1.18193f,       // humidity_diff ()
        -0.000639384f,  // pressure ()
        -0.298502f,     // pressure_diff ()
        -0.210775f,     // gas_resistance ()
        -0.087954f     // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        0.107383f,      // temperature ()
        0.342512f,      // temperature_diff ()
        -0.125204f,     // humidity ()
        1.18193f,       // humidity_diff ()
        -0.000639384f,  // pressure ()
        -0.298502f,     // pressure_diff ()
        -0.210775f,     // gas_resistance ()
        -0.087954f     // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        0.105493f,      // temperature ()
        -0.100359f,     // temperature_diff ()
        -0.123939f,     // humidity ()
        -0.354843f,     // humidity_diff ()
        -0.000865567f,  // pressure ()
        -0.096866f,     // pressure_diff ()
        -0.041709f,     // gas_resistance ()
        -0.309593f     // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        0.105493f,      // temperature ()
        -0.100359f,     // temperature_diff ()
        -0.123939f,     // humidity ()
        -0.354843f,     // humidity_diff ()
        -0.000865567f,  // pressure ()
        -0.096866f,     // pressure_diff ()
        -0.041709f,     // gas_resistance ()
        -0.309593f     // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        0.105493f,      // temperature ()
        -0.100359f,     // temperature_diff ()
        -0.123939f,     // humidity ()
        -0.354843f,     // humidity_diff ()
        -0.000865567f,  // pressure ()
        -0.096866f,     // pressure_diff ()
        -0.041709f,     // gas_resistance ()
        -0.309593f     // gas_resistance_diff ()
    }
};

/* Per-step, per-feature std   [heater_step][feature_index]  (0.0 = pass-through) */
const float FEATURE_STD[10][8] = {
    /* [320 °C] */
    {
        0.0811039f,  // temperature ()
        0.747111f,   // temperature_diff ()
        0.136279f,   // humidity ()
        8.36165f,    // humidity_diff ()
        0.0366643f,  // pressure ()
        8.36416f,    // pressure_diff ()
        0.250163f,   // gas_resistance ()
        1.54948f    // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        0.0816801f,  // temperature ()
        3.73474f,    // temperature_diff ()
        0.136743f,   // humidity ()
        3.5459f,     // humidity_diff ()
        0.0366746f,  // pressure ()
        12.1295f,    // pressure_diff ()
        0.423209f,   // gas_resistance ()
        2.05551f    // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        0.0816801f,  // temperature ()
        3.73474f,    // temperature_diff ()
        0.136743f,   // humidity ()
        3.5459f,     // humidity_diff ()
        0.0366746f,  // pressure ()
        12.1295f,    // pressure_diff ()
        0.423209f,   // gas_resistance ()
        2.05551f    // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        0.0816801f,  // temperature ()
        3.73474f,    // temperature_diff ()
        0.136743f,   // humidity ()
        3.5459f,     // humidity_diff ()
        0.0366746f,  // pressure ()
        12.1295f,    // pressure_diff ()
        0.423209f,   // gas_resistance ()
        2.05551f    // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        0.0815408f,  // temperature ()
        2.93493f,    // temperature_diff ()
        0.136134f,   // humidity ()
        21.7499f,    // humidity_diff ()
        0.0366734f,  // pressure ()
        13.0659f,    // pressure_diff ()
        0.320959f,   // gas_resistance ()
        1.42856f    // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        0.0815408f,  // temperature ()
        2.93493f,    // temperature_diff ()
        0.136134f,   // humidity ()
        21.7499f,    // humidity_diff ()
        0.0366734f,  // pressure ()
        13.0659f,    // pressure_diff ()
        0.320959f,   // gas_resistance ()
        1.42856f    // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        0.0815408f,  // temperature ()
        2.93493f,    // temperature_diff ()
        0.136134f,   // humidity ()
        21.7499f,    // humidity_diff ()
        0.0366734f,  // pressure ()
        13.0659f,    // pressure_diff ()
        0.320959f,   // gas_resistance ()
        1.42856f    // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        0.0811039f,  // temperature ()
        0.747111f,   // temperature_diff ()
        0.136279f,   // humidity ()
        8.36165f,    // humidity_diff ()
        0.0366643f,  // pressure ()
        8.36416f,    // pressure_diff ()
        0.250163f,   // gas_resistance ()
        1.54948f    // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        0.0811039f,  // temperature ()
        0.747111f,   // temperature_diff ()
        0.136279f,   // humidity ()
        8.36165f,    // humidity_diff ()
        0.0366643f,  // pressure ()
        8.36416f,    // pressure_diff ()
        0.250163f,   // gas_resistance ()
        1.54948f    // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        0.0811039f,  // temperature ()
        0.747111f,   // temperature_diff ()
        0.136279f,   // humidity ()
        8.36165f,    // humidity_diff ()
        0.0366643f,  // pressure ()
        8.36416f,    // pressure_diff ()
        0.250163f,   // gas_resistance ()
        1.54948f    // gas_resistance_diff ()
    }
};

#endif /* STATISTICS_H */
