#!/usr/bin/env python3
"""
csv_to_statistics_h.py
=======================
Convert training data statistics into the ``statistics.h`` header used by the
real_time_inference Arduino sketch.

The output always uses **2-D arrays** indexed as
``FEATURE_MEAN[heater_step][feature]``, with a ``STATS_SEQ_LEN`` constant that
tells the sketch the number of heater steps.

  • Forced-mode models (one heater step) → ``STATS_SEQ_LEN = 1``
  • Sequential / LSTM models (N heater steps) → ``STATS_SEQ_LEN = N``

Modes
-----
**Describe mode** (default) — one set of global statistics, SEQ_LEN = 1.
Input must be the output of ``df[feature_columns].describe().to_csv("stats.csv")``.

    python csv_to_statistics_h.py stats.csv
    python csv_to_statistics_h.py stats.csv -o sketches/real_time_inference/statistics.h

**By-position mode** — per-step statistics keyed on heater step index,
SEQ_LEN = number of distinct positions.  Input must be the raw data CSV.

    python csv_to_statistics_h.py data.csv --by-position
    python csv_to_statistics_h.py data.csv --by-position --position-col heater_step

**By-plate-temperature mode** — per-step statistics keyed on unique plate
temperature values, sorted ascending.  Rows with the same plate temperature
are pooled together (useful when multiple positions share a temperature).
SEQ_LEN = number of distinct plate temperatures.

    python csv_to_statistics_h.py data.csv --by-plate-temperature
    python csv_to_statistics_h.py data.csv --by-plate-temperature --temp-col plate_temperature

**By-temp mode** — per-step statistics following an explicit temperature
profile.  Each element in the profile maps to one heater step; rows at the
same temperature are pooled.  SEQ_LEN = len(profile).

    python csv_to_statistics_h.py data.csv --by-temp
    python csv_to_statistics_h.py data.csv --by-temp --temp-profile 320 100 100 200 200 200 320 320 320

Common options
--------------
    --features  plate_temperature heater_duration temperature pressure humidity gas_resistance
    --passthrough  plate_temperature heater_duration
    --units  °C ms °C hPa % Ω
"""

import argparse
import csv
import sys
from datetime import datetime, timezone
from pathlib import Path

# ── Default configuration ──────────────────────────────────────────────────────

# (column_name, unit, pass_through)
#   pass_through=True  →  FEATURE_STD entry is forced to 0.0 (no standardisation)
DEFAULT_FEATURES: list[tuple[str, str, bool]] = [
    ("plate_temperature", "°C",  True),
    ("heater_duration",   "ms",  True),
    ("temperature",       "°C",  False),
    ("pressure",          "hPa", False),
    ("humidity",          "%",   False),
    ("gas_resistance",    "Ω",   False),
]

# ── Templates ──────────────────────────────────────────────────────────────────

_HEADER_TEMPLATE = """\
/**
 * Training data statistics for feature standardisation.
 *
 * Auto-generated by csv_to_statistics_h.py
 * Timestamp  : {timestamp}
 * Source     : {source}
 * Mode       : {mode}
 *
 * z-score normalisation applied per heater step:
 *
 *   z = (x - FEATURE_MEAN[step][i]) / FEATURE_STD[step][i]
 *
 * Features where FEATURE_STD[step][i] == 0.0 are passed through unchanged.
 * STATS_SEQ_LEN == 1 for forced-mode (single-step) models.
 *
 * Feature order — must match the order used when training the model:
{feature_index_comment}
 */

#ifndef STATISTICS_H
#define STATISTICS_H

constexpr int STATS_SEQ_LEN = {seq_len};

/* Per-step, per-feature mean  [heater_step][feature_index] */
const float FEATURE_MEAN[{seq_len}][{n}] = {{
{mean_rows}
}};

/* Per-step, per-feature std   [heater_step][feature_index]  (0.0 = pass-through) */
const float FEATURE_STD[{seq_len}][{n}] = {{
{std_rows}
}};

#endif /* STATISTICS_H */
"""

# ── Helpers ────────────────────────────────────────────────────────────────────


def _read_describe_csv(path: Path) -> dict[str, dict[str, float]]:
    """Return {stat_name: {column: value}} for all rows in a describe() CSV."""
    with path.open(newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        if reader.fieldnames is None:
            raise ValueError("CSV appears to be empty.")
        index_key = reader.fieldnames[0]
        rows: dict[str, dict[str, float]] = {}
        for row in reader:
            stat = row.pop(index_key).strip()
            rows[stat] = {col.strip(): float(val) for col, val in row.items() if val.strip()}
    return rows


def _read_raw_csv_by_temp_profile(
    path: Path,
    temp_col: str,
    profile: list[int],
) -> list[tuple[int, dict[str, dict[str, float]]]]:
    """Read raw CSV and return per-step statistics following a temperature profile.

    Returns a list of ``(temperature, {"mean": {...}, "std": {...}})`` tuples,
    one entry per element in *profile*, in order.  Rows sharing the same
    temperature are pooled to compute each step's statistics.
    """
    try:
        import pandas as pd
    except ImportError:
        print("ERROR: --by-temp requires pandas.  Install it with: pip install pandas",
              file=sys.stderr)
        sys.exit(1)

    df = pd.read_csv(path)
    if temp_col not in df.columns:
        raise KeyError(
            f"Temperature column '{temp_col}' not found in CSV.  "
            f"Available columns: {list(df.columns)}"
        )

    # Pre-compute stats per unique temperature in the profile (pool rows)
    temp_stats: dict[int, dict[str, dict[str, float]]] = {}
    for temp in set(profile):
        sub = df[df[temp_col] == temp]
        if sub.empty:
            raise ValueError(
                f"No rows found for temperature {temp} in column '{temp_col}'.  "
                f"Available: {sorted(df[temp_col].unique().tolist())}"
            )
        temp_stats[temp] = {
            "mean": sub.mean(numeric_only=True).to_dict(),
            "std":  sub.std(numeric_only=True).to_dict(),
        }

    return [(temp, temp_stats[temp]) for temp in profile]


def _read_raw_csv_by_position(
    path: Path,
    position_col: str,
) -> list[tuple[int, dict[str, dict[str, float]]]]:
    """Read the raw data CSV and return per-position statistics.

    Returns a list of ``(position_index, {"mean": {...}, "std": {...}})`` tuples
    sorted by position value, one entry per distinct value in *position_col*.
    """
    try:
        import pandas as pd
    except ImportError:
        print("ERROR: --by-position requires pandas.  Install it with: pip install pandas",
              file=sys.stderr)
        sys.exit(1)

    df = pd.read_csv(path)
    if position_col not in df.columns:
        raise KeyError(
            f"Position column '{position_col}' not found in CSV.  "
            f"Available columns: {list(df.columns)}"
        )

    result: list[tuple[int, dict[str, dict[str, float]]]] = []
    for pos in sorted(df[position_col].unique()):
        sub = df[df[position_col] == pos]
        stats = {
            "mean": sub.mean(numeric_only=True).to_dict(),
            "std":  sub.std(numeric_only=True).to_dict(),
        }
        result.append((int(pos), stats))
    return result


def _float_literal(value: float) -> str:
    """Format a float as a C float literal, e.g. 3.14159f."""
    if value == 0.0:
        return "0.0f"
    s = f"{value:.6g}"
    if "." not in s and "e" not in s:
        s += ".0"
    return s + "f"


def _build_feature_index_comment(features: list[tuple[str, str, bool]]) -> str:
    """Build the ' *   [i]  name  (unit)' block for the file header."""
    lines = []
    for i, (name, unit, passthrough) in enumerate(features):
        suffix = "  — pass-through" if passthrough else ""
        lines.append(f" *   [{i}]  {name:<24} ({unit}){suffix}")
    return "\n".join(lines)


def _build_row(
    features: list[tuple[str, str, bool]],
    values: list[float],
    array_role: str,  # "mean" or "std"
    step_label: str,  # e.g. "step 0 — plate_temperature = 320 °C"
    is_last: bool,
) -> str:
    """Build one inner row of the 2-D C array, with an inline step comment."""
    literals = [_float_literal(v) for v in values]
    max_lit_len = max(len(lit) for lit in literals)
    entries = []
    for i, ((name, unit, passthrough), lit) in enumerate(zip(features, literals)):
        comma = "," if i < len(features) - 1 else ""
        pad = " " * (max_lit_len - len(lit))
        note = "pass-through" if (array_role == "std" and passthrough) else unit
        entries.append(f"        {lit}{comma}{pad}  // {name} ({note})")
    row_comma = "" if is_last else ","
    inner = "\n".join(entries)
    return f"    /* [{step_label}] */\n    {{\n{inner}\n    }}{row_comma}"


def _build_2d_array(
    steps: list[tuple[str, list[float]]],  # [(label, values), ...]
    features: list[tuple[str, str, bool]],
    array_role: str,
) -> str:
    """Assemble all rows into the body of the 2-D array."""
    rows = []
    for i, (label, values) in enumerate(steps):
        rows.append(_build_row(features, values, array_role, label,
                               is_last=(i == len(steps) - 1)))
    return "\n".join(rows)


def _extract_step_vectors(
    stats: dict[str, dict[str, float]],
    features: list[tuple[str, str, bool]],
    step_label: str,
) -> tuple[list[float], list[float]]:
    """Extract mean and std vectors for one step from a stats dict."""
    mean_row = stats.get("mean", stats)  # allow flat dicts too
    std_row  = stats.get("std",  stats)

    means: list[float] = []
    stds:  list[float] = []
    for name, _unit, passthrough in features:
        if name not in mean_row:
            raise KeyError(
                f"Column '{name}' not found in stats for {step_label}.  "
                f"Available: {list(mean_row.keys())}"
            )
        means.append(mean_row[name])
        stds.append(0.0 if passthrough else std_row.get(name, 0.0))
    return means, stds


def generate(
    per_step_stats: list[tuple[str, dict[str, dict[str, float]]]],
    features: list[tuple[str, str, bool]],
    source_name: str,
    mode_label: str,
) -> str:
    """Render and return the complete statistics.h content.

    Parameters
    ----------
    per_step_stats:
        List of ``(step_label, {"mean": {...}, "std": {...}})`` — one entry per
        heater step.  For forced / describe mode this list has length 1.
    features:
        Ordered feature list as ``(column_name, unit, pass_through)``.
    source_name:
        Human-readable source identifier written into the file comment.
    mode_label:
        Short description of the generation mode for the file comment.
    """
    seq_len = len(per_step_stats)
    n = len(features)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    mean_steps: list[tuple[str, list[float]]] = []
    std_steps:  list[tuple[str, list[float]]] = []

    for label, stats in per_step_stats:
        means, stds = _extract_step_vectors(stats, features, label)
        mean_steps.append((label, means))
        std_steps.append((label, stds))

    return _HEADER_TEMPLATE.format(
        timestamp=timestamp,
        source=source_name,
        mode=mode_label,
        feature_index_comment=_build_feature_index_comment(features),
        seq_len=seq_len,
        n=n,
        mean_rows=_build_2d_array(mean_steps, features, "mean"),
        std_rows= _build_2d_array(std_steps,  features, "std"),
    )


# ── CLI ────────────────────────────────────────────────────────────────────────


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Convert training data statistics to a 2-D statistics.h Arduino header. "
            "Use --by-position for sequential / LSTM models with per-step statistics."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "input",
        metavar="CSV",
        help=(
            "Describe mode (default): CSV produced by df.describe().to_csv().  "
            "By-position mode (--by-position): raw data CSV with a position column."
        ),
    )
    parser.add_argument(
        "-o", "--output",
        metavar="OUTPUT_H",
        default=None,
        help="Path to write statistics.h  [default: statistics.h next to input file]",
    )
    mode_group = parser.add_mutually_exclusive_group()
    mode_group.add_argument(
        "--by-position",
        action="store_true",
        dest="by_position",
        help=(
            "Compute per-heater-step statistics from a raw data CSV.  "
            "Groups rows by the position column (see --position-col) and emits "
            "STATS_SEQ_LEN = <number of distinct positions>."
        ),
    )
    mode_group.add_argument(
        "--by-plate-temperature",
        action="store_true",
        dest="by_plate_temperature",
        help=(
            "Compute per-temperature statistics from a raw data CSV.  "
            "Groups rows by unique plate temperature values (see --temp-col), "
            "sorted ascending, and emits STATS_SEQ_LEN = <number of distinct temperatures>.  "
            "Rows with the same plate temperature are pooled across positions."
        ),
    )
    mode_group.add_argument(
        "--by-temp",
        action="store_true",
        dest="by_temp",
        help=(
            "Compute per-step statistics from a raw data CSV following an explicit "
            "temperature profile (see --temp-profile).  Each profile element maps to "
            "one heater step; rows at that temperature are pooled.  "
            "STATS_SEQ_LEN = len(profile)."
        ),
    )
    parser.add_argument(
        "--temp-profile",
        nargs="+",
        metavar="TEMP",
        type=int,
        default=[320, 100, 100, 200, 200, 200, 320, 320, 320],
        dest="temp_profile",
        help=(
            "Temperature profile as a space-separated sequence of setpoints (°C), "
            "one per heater step.  Only used with --by-temp.  "
            "Default: 320 100 100 200 200 200 320 320 320 (standard BME profile)."
        ),
    )
    parser.add_argument(
        "--position-col",
        metavar="COL",
        default="position",
        dest="position_col",
        help="Name of the heater-step column in the raw CSV  [default: position]",
    )
    parser.add_argument(
        "--temp-col",
        metavar="COL",
        default="plate_temperature",
        dest="temp_col",
        help="Name of the plate-temperature column in the raw CSV  [default: plate_temperature]",
    )
    parser.add_argument(
        "--features",
        nargs="+",
        metavar="COL",
        default=None,
        help=(
            "Ordered list of feature column names matching the model's input order.  "
            "Overrides the built-in default."
        ),
    )
    parser.add_argument(
        "--units",
        nargs="+",
        metavar="UNIT",
        default=None,
        help="Unit strings for each feature (same order as --features, used in comments).",
    )
    parser.add_argument(
        "--passthrough",
        nargs="*",
        metavar="COL",
        default=None,
        help=(
            "Columns that should NOT be standardised (std forced to 0.0).  "
            "Defaults to 'plate_temperature heater_duration' for the built-in feature list."
        ),
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = _parse_args(argv)

    input_path = Path(args.input)
    if not input_path.is_file():
        print(f"ERROR: input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    output_path = Path(args.output) if args.output else input_path.with_name("statistics.h")

    # Build feature list
    if args.features is None:
        features = DEFAULT_FEATURES
    else:
        col_names = args.features
        units = args.units or [""] * len(col_names)
        if len(units) != len(col_names):
            print("ERROR: --units must have the same number of entries as --features.",
                  file=sys.stderr)
            sys.exit(1)
        passthrough_set = set(args.passthrough) if args.passthrough is not None else set()
        features = [(name, unit, name in passthrough_set)
                    for name, unit in zip(col_names, units)]

    # ── Load statistics ────────────────────────────────────────────────────────
    if args.by_position:
        mode_label = f"by-position (column '{args.position_col}')"
        try:
            raw_steps = _read_raw_csv_by_position(input_path, args.position_col)
        except Exception as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            sys.exit(1)

        per_step_stats = [
            (f"step {pos}", {"mean": s["mean"], "std": s["std"]})
            for pos, s in raw_steps
        ]

    elif args.by_plate_temperature:
        mode_label = f"by-plate-temperature (column '{args.temp_col}')"
        try:
            raw_steps = _read_raw_csv_by_position(input_path, args.temp_col)
        except Exception as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            sys.exit(1)

        per_step_stats = [
            (f"{int(temp)} °C", {"mean": s["mean"], "std": s["std"]})
            for temp, s in raw_steps
        ]

    elif args.by_temp:
        profile = args.temp_profile
        mode_label = (
            f"by-temp-profile (column '{args.temp_col}', "
            f"profile: {' '.join(str(t) for t in profile)})"
        )
        try:
            raw_steps = _read_raw_csv_by_temp_profile(input_path, args.temp_col, profile)
        except Exception as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            sys.exit(1)

        per_step_stats = [
            (f"{temp} °C", {"mean": s["mean"], "std": s["std"]})
            for temp, s in raw_steps
        ]

    else:
        mode_label = "describe (global, SEQ_LEN = 1)"
        try:
            stats = _read_describe_csv(input_path)
        except Exception as exc:
            print(f"ERROR reading CSV: {exc}", file=sys.stderr)
            sys.exit(1)
        if "mean" not in stats:
            print("ERROR: 'mean' row not found — is this a describe() CSV?  "
                  "For raw data use --by-position or --by-plate-temperature.", file=sys.stderr)
            sys.exit(1)
        per_step_stats = [("step 0 — global", stats)]

    # ── Generate and write ─────────────────────────────────────────────────────
    try:
        content = generate(per_step_stats, features,
                           source_name=input_path.name, mode_label=mode_label)
    except (KeyError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"Wrote {output_path}  (STATS_SEQ_LEN = {len(per_step_stats)})")

    # ── Summary table ──────────────────────────────────────────────────────────
    print()
    header = f"  {'Step':>4}  {'Feature':<24}  {'Mean':>14}  {'Std':>14}  Standardised"
    print(header)
    print("  " + "-" * (len(header) - 2))
    for step_label, stats in per_step_stats:
        mean_row = stats["mean"]
        std_row  = stats["std"]
        for name, unit, passthrough in features:
            mean_val = mean_row.get(name, float("nan"))
            std_val  = 0.0 if passthrough else std_row.get(name, float("nan"))
            flag = "no (pass-through)" if passthrough else "yes"
            print(f"  {step_label:>4}  {name:<24}  {mean_val:>14.4g}  {std_val:>14.4g}  {flag}")
        print()


if __name__ == "__main__":
    main()
