#!/usr/bin/env python3
"""
csv_to_statistics_h.py

Convert a pandas describe() CSV export into the statistics.h header used by
the real_time_inference Arduino sketch.

The input CSV must be the output of:

    df[feature_columns].describe().to_csv("stats.csv")

Expected index values in the first column: count, mean, std, min, 25%, 50%,
75%, max.  Only 'mean' and 'std' are used.

Usage
-----
    # Minimal — uses built-in default feature order and guesses output path
    python csv_to_statistics_h.py stats.csv

    # Specify output path explicitly
    python csv_to_statistics_h.py stats.csv -o sketches/real_time_inference/statistics.h

    # Override the feature order (must match model input order)
    python csv_to_statistics_h.py stats.csv \\
        --features plate_temperature heater_duration temperature pressure humidity gas_resistance

    # Mark specific features as pass-through (std forced to 0, mean kept as-is)
    python csv_to_statistics_h.py stats.csv --passthrough plate_temperature heater_duration
"""

import argparse
import csv
import sys
from datetime import datetime, timezone
from pathlib import Path

# ── Default configuration ──────────────────────────────────────────────────────

# (column_name, unit, pass_through)
#   pass_through=True  →  FEATURE_STD entry is forced to 0.0 (no standardisation)
DEFAULT_FEATURES: list[tuple[str, str, bool]] = [
    ("plate_temperature", "°C",  True),
    ("heater_duration",   "ms",  True),
    ("temperature",       "°C",  False),
    ("pressure",          "hPa", False),
    ("humidity",          "%",   False),
    ("gas_resistance",    "Ω",   False),
]

# ── Template ───────────────────────────────────────────────────────────────────

_HEADER_TEMPLATE = """\
/**
 * Training data statistics for feature standardisation.
 *
 * Auto-generated by csv_to_statistics_h.py
 * Timestamp : {timestamp}
 * Source    : {source}
 *
 * Used to z-score normalise each sensor reading before passing it to the
 * model:
 *
 *   z = (x - mean) / std      (features where std != 0.0)
 *
 * Features where std == 0.0 are passed through unchanged.
 *
 * Feature order — must match the order used when training the model:
{feature_index_comment}
 */

#ifndef STATISTICS_H
#define STATISTICS_H

/* Per-feature mean of the training set */
const float FEATURE_MEAN[{n}] = {{
{mean_entries}
}};

/* Per-feature standard deviation of the training set (0.0 = pass-through) */
const float FEATURE_STD[{n}] = {{
{std_entries}
}};

#endif /* STATISTICS_H */
"""

# ── Helpers ────────────────────────────────────────────────────────────────────


def _read_describe_csv(path: Path) -> dict[str, dict[str, float]]:
    """Return {stat_name: {column: value}} for all rows in a describe() CSV."""
    with path.open(newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        # The first field (index column) has an empty or unnamed header.
        # csv.DictReader gives it the key '' or 'Unnamed: 0' depending on
        # how the CSV was written.  Detect it as the first key.
        if reader.fieldnames is None:
            raise ValueError("CSV appears to be empty.")
        index_key = reader.fieldnames[0]
        rows: dict[str, dict[str, float]] = {}
        for row in reader:
            stat = row.pop(index_key).strip()
            rows[stat] = {col.strip(): float(val) for col, val in row.items() if val.strip()}
    return rows


def _float_literal(value: float) -> str:
    """Format a float as a C float literal, e.g. 3.14159f."""
    if value == 0.0:
        return "0.0f"
    # Use enough precision for single-precision floats (~7 significant digits)
    s = f"{value:.6g}"
    # Ensure there is a decimal point so it reads as floating-point
    if "." not in s and "e" not in s:
        s += ".0"
    return s + "f"


def _build_feature_index_comment(features: list[tuple[str, str, bool]]) -> str:
    """Build the ' *   [i]  name  (unit)' block for the file header."""
    lines = []
    for i, (name, unit, passthrough) in enumerate(features):
        suffix = "  — pass-through" if passthrough else ""
        lines.append(f" *   [{i}]  {name:<24} ({unit}){suffix}")
    return "\n".join(lines)


def _build_array_entries(
    features: list[tuple[str, str, bool]],
    values: list[float],
    array_role: str,  # "mean" or "std"
) -> str:
    """Build indented C array entries with inline comments."""
    # Align the value literals and comments
    literals = [_float_literal(v) for v in values]
    max_lit_len = max(len(lit) for lit in literals)
    lines = []
    for i, ((name, unit, passthrough), lit) in enumerate(zip(features, literals)):
        comma = "," if i < len(features) - 1 else " "
        pad = " " * (max_lit_len - len(lit))
        note = "pass-through" if (array_role == "std" and passthrough) else f"{unit}"
        lines.append(f"    {lit}{comma}{pad}  // {name:<24} ({note})")
    return "\n".join(lines)


def generate(
    stats: dict[str, dict[str, float]],
    features: list[tuple[str, str, bool]],
    source_name: str,
) -> str:
    """Render and return the complete statistics.h content."""
    if "mean" not in stats:
        raise KeyError("'mean' row not found in the describe() CSV.")
    if "std" not in stats:
        raise KeyError("'std' row not found in the describe() CSV.")

    mean_row = stats["mean"]
    std_row = stats["std"]

    means: list[float] = []
    stds: list[float] = []

    for name, _unit, passthrough in features:
        if name not in mean_row:
            raise KeyError(
                f"Column '{name}' not found in the CSV.  "
                f"Available columns: {list(mean_row.keys())}"
            )
        means.append(mean_row[name])
        stds.append(0.0 if passthrough else std_row[name])

    n = len(features)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return _HEADER_TEMPLATE.format(
        timestamp=timestamp,
        source=source_name,
        feature_index_comment=_build_feature_index_comment(features),
        n=n,
        mean_entries=_build_array_entries(features, means, "mean"),
        std_entries=_build_array_entries(features, stds, "std"),
    )


# ── CLI ────────────────────────────────────────────────────────────────────────


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert a pandas describe() CSV to a statistics.h Arduino header.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "input",
        metavar="STATS_CSV",
        help="Path to the CSV produced by df.describe().to_csv()",
    )
    parser.add_argument(
        "-o", "--output",
        metavar="OUTPUT_H",
        default=None,
        help=(
            "Path to write statistics.h  "
            "[default: statistics.h next to the input file]"
        ),
    )
    parser.add_argument(
        "--features",
        nargs="+",
        metavar="COL",
        default=None,
        help=(
            "Ordered list of feature column names as they appear in the CSV "
            "AND as the model expects them.  Overrides the built-in default."
        ),
    )
    parser.add_argument(
        "--units",
        nargs="+",
        metavar="UNIT",
        default=None,
        help=(
            "Unit strings for each feature (same order as --features).  "
            "Used only in comments.  Defaults to empty strings when --features "
            "is provided without --units."
        ),
    )
    parser.add_argument(
        "--passthrough",
        nargs="*",
        metavar="COL",
        default=None,
        help=(
            "Columns that should NOT be standardised (std forced to 0.0).  "
            "Defaults to 'plate_temperature heater_duration' when using the "
            "built-in feature list."
        ),
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = _parse_args(argv)

    input_path = Path(args.input)
    if not input_path.is_file():
        print(f"ERROR: input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    # Resolve output path
    if args.output is None:
        output_path = input_path.with_name("statistics.h")
    else:
        output_path = Path(args.output)

    # Build feature list
    if args.features is None:
        features = DEFAULT_FEATURES
    else:
        col_names = args.features
        units = args.units or [""] * len(col_names)
        if len(units) != len(col_names):
            print(
                "ERROR: --units must have the same number of entries as --features.",
                file=sys.stderr,
            )
            sys.exit(1)
        passthrough_set = set(args.passthrough) if args.passthrough is not None else set()
        features = [(name, unit, name in passthrough_set) for name, unit in zip(col_names, units)]

    # Parse CSV
    try:
        stats = _read_describe_csv(input_path)
    except Exception as exc:
        print(f"ERROR reading CSV: {exc}", file=sys.stderr)
        sys.exit(1)

    # Generate header
    try:
        content = generate(stats, features, source_name=input_path.name)
    except (KeyError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)

    # Write output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"Wrote {output_path}")

    # Print a brief summary
    mean_row = stats["mean"]
    std_row  = stats["std"]
    print(f"\n  {'Feature':<24}  {'Mean':>14}  {'Std':>14}  Standardised")
    print(f"  {'-'*24}  {'-'*14}  {'-'*14}  ------------")
    for name, unit, passthrough in features:
        mean_val = mean_row.get(name, float("nan"))
        std_val  = 0.0 if passthrough else std_row.get(name, float("nan"))
        flag = "no (pass-through)" if passthrough else "yes"
        print(f"  {name:<24}  {mean_val:>14.4g}  {std_val:>14.4g}  {flag}")


if __name__ == "__main__":
    main()
