#!/usr/bin/env python3
"""
model_to_tflite.py
==================
Convert a trained Keras model to LiteRT (TFLite) format and emit an Arduino
header file containing the model as a C byte array.

Two usage modes
---------------
**As a module** (call from your training notebook / script):

    from scripts.model_to_tflite import convert

    convert(
        model,                          # trained keras.Model
        tflite_path="model.tflite",
        header_path="model.h",
    )

**As a CLI tool** (pass a SavedModel or .keras path):

    python model_to_tflite.py saved_model_dir/ -o model.tflite --header model.h

    # With post-training quantisation (reduces model size ~4×, slight accuracy drop)
    python model_to_tflite.py saved_model_dir/ --quantize

LSTM compatibility
------------------
Keras LSTM uses a dynamic ``TensorListReserve`` op internally.  The default
TFLite builtin ops cannot handle the dynamic element shape, causing:

    'tf.TensorListReserve' op requires element_shape to be static

**Fix A — retrain with ``unroll=True`` (recommended for Arduino / TFLite Micro)**

    model.add(LSTM(16, return_sequences=False, unroll=True))

  Unrolling expands the recurrent loop into explicit timestep operations at
  graph-build time, removing all dynamic tensor-list ops.  This is the only
  option that produces a model compatible with TFLite Micro on microcontrollers.

**Fix B — Select TF ops (desktop / mobile only, NOT supported on Arduino)**

    python model_to_tflite.py model.keras --select-ops

  Enables ``tf.lite.OpsSet.SELECT_TF_OPS``, which keeps the TF kernel for ops
  that have no native TFLite builtin.  The resulting ``.tflite`` file requires
  the ``libtensorflow_lite_select_ops`` runtime library, which is not available
  on TFLite Micro / Arduino.

``SimpleRNN`` avoids the problem too, but ``LSTM(unroll=True)`` is preferable
because it keeps the gating mechanism without any compatibility compromises.

Output
------
  <tflite_path>  — binary LiteRT flatbuffer
  <header_path>  — C/C++ header with the model as a byte array, e.g.:

    alignas(8) const unsigned char g_model[] = { 0x1c, 0x00, ... };
    const unsigned int g_model_len = sizeof(g_model);

The `alignas(8)` is required by TensorFlow Lite Micro.
"""

import argparse
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path

# ── Template ───────────────────────────────────────────────────────────────────

_HEADER_TEMPLATE = """\
/**
 * TFLite / LiteRT model byte array.
 *
 * Auto-generated by model_to_tflite.py
 * Timestamp  : {timestamp}
 * Source     : {source}
 * Model size : {size_bytes} bytes
 * Quantized  : {quantized}
 *
 * Usage (Arduino / TFLite Micro):
 *
 *   #include "model.h"
 *   const tflite::Model* model = tflite::GetModel(g_model);
 */

#ifndef MODEL_H
#define MODEL_H

/* 8-byte alignment required by TFLite Micro */
alignas(8) const unsigned char g_model[] = {{
{hex_array}
}};

const unsigned int g_model_len = sizeof(g_model);

#endif /* MODEL_H */
"""

# ── Core conversion ────────────────────────────────────────────────────────────


def _bytes_to_c_array(data: bytes, cols: int = 12) -> str:
    """Format raw bytes as a C hex-literal array body (indented, `cols` per line)."""
    hex_vals = [f"0x{b:02x}" for b in data]
    lines = []
    for i in range(0, len(hex_vals), cols):
        chunk = hex_vals[i : i + cols]
        lines.append("    " + ", ".join(chunk) + ",")
    # Remove trailing comma from the last element so C89 compilers are happy
    if lines:
        lines[-1] = lines[-1].rstrip(",")
    return "\n".join(lines)


_TENSORLIST_ERROR_HINT = """
CONVERSION FAILED — dynamic TensorList op detected (common with Keras LSTM).

Fix A  ── retrain with unroll=True  (works on Arduino / TFLite Micro)
    model.add(LSTM(16, return_sequences=False, unroll=True))

    The conversion script also traces the model with a fixed batch size of 1
    so that the zero-state SHAPE → FILL chain is constant-folded away.
    TFLite Micro's FILL kernel only accepts constant dims tensors; this avoids
    the "Non-constant >dims< tensor is not supported" error.

Fix B  ── use Select TF ops  (desktop / mobile only, NOT for Arduino)
    convert(..., select_ops=True)
    # or on the CLI: --select-ops

See the module docstring for full details.
"""


def convert(
    model,
    tflite_path: str | Path = "model.tflite",
    header_path: str | Path = "model.h",
    quantize: bool = False,
    representative_dataset=None,
    select_ops: bool = False,
) -> bytes:
    """Convert *model* to LiteRT, save the .tflite file and the C header.

    Parameters
    ----------
    model:
        A trained ``keras.Model`` instance.
    tflite_path:
        Where to write the ``.tflite`` flatbuffer.
    header_path:
        Where to write the Arduino ``model.h`` header.
    quantize:
        If ``True``, apply full-integer post-training quantisation (INT8).
        Requires *representative_dataset* to calibrate the activations.
    representative_dataset:
        A callable with no arguments that yields batches of input data as numpy
        arrays shaped ``(1, SEQ_LEN, NUM_FEATURES)``.  Only used when
        ``quantize=True``.  Example::

            def representative_dataset():
                for sample in X_train[:100]:
                    yield [sample[np.newaxis].astype(np.float32)]

    select_ops:
        If ``True``, enable ``SELECT_TF_OPS`` to allow ops without a native
        TFLite builtin (e.g. dynamic LSTM tensor-list ops).  The resulting
        model requires the ``libtensorflow_lite_select_ops`` runtime and is
        **NOT compatible with TFLite Micro / Arduino**.  For Arduino, retrain
        with ``LSTM(unroll=True)`` instead.

    Returns
    -------
    bytes
        The raw TFLite flatbuffer (same content as the saved ``.tflite`` file).
    """
    import tensorflow as tf  # local import — keeps the module importable without TF

    tflite_path = Path(tflite_path)
    header_path = Path(header_path)

    # ── Convert ───────────────────────────────────────────────────────────────
    # Fix the batch dimension to 1 before conversion.
    #
    # Keras LSTM without explicit initial states generates zero states at
    # runtime via  tf.shape(inputs)[0] → FILL.  TFLite Micro's FILL kernel
    # requires a *compile-time constant* dims tensor — a runtime SHAPE output
    # does not satisfy this ("Non-constant >dims< tensor is not supported").
    #
    # Tracing with a concrete batch-size-1 signature makes tf.shape(inputs)[0]
    # a known constant (1), so the compiler folds the entire SHAPE → FILL chain
    # into constant tensors.  Neither SHAPE nor FILL appears in the flatbuffer.
    input_shape = [1] + list(model.input_shape[1:])  # replace None batch with 1
    run_fn = tf.function(lambda x: model(x, training=False))
    concrete_fn = run_fn.get_concrete_function(
        tf.TensorSpec(input_shape, dtype=model.inputs[0].dtype)
    )
    converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_fn], model)

    if select_ops:
        print(
            "  WARNING: SELECT_TF_OPS enabled — output is NOT compatible with "
            "TFLite Micro / Arduino.  Retrain with LSTM(unroll=True) for MCU targets.",
            file=sys.stderr,
        )
        converter.target_spec.supported_ops = [
            tf.lite.OpsSet.TFLITE_BUILTINS,
            tf.lite.OpsSet.SELECT_TF_OPS,
        ]
        converter._experimental_lower_tensor_list_ops = False

    if quantize:
        if representative_dataset is None:
            raise ValueError(
                "representative_dataset must be provided when quantize=True."
            )
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.representative_dataset = representative_dataset
        if not select_ops:
            converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type  = tf.int8
        converter.inference_output_type = tf.int8

    print("Converting model to LiteRT …", flush=True)
    try:
        tflite_model: bytes = converter.convert()
    except Exception as exc:
        if "TensorListReserve" in str(exc) or "tensor_list" in str(exc).lower():
            print(_TENSORLIST_ERROR_HINT, file=sys.stderr)
        raise
    print(f"  Model size: {len(tflite_model):,} bytes")

    # ── Save .tflite ─────────────────────────────────────────────────────────
    tflite_path.parent.mkdir(parents=True, exist_ok=True)
    tflite_path.write_bytes(tflite_model)
    print(f"  Saved .tflite → {tflite_path}")

    # ── Write header ─────────────────────────────────────────────────────────
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    content = _HEADER_TEMPLATE.format(
        timestamp=timestamp,
        source=tflite_path.name,
        size_bytes=f"{len(tflite_model):,}",
        quantized="yes (INT8)" if quantize else "no (float32)",
        hex_array=_bytes_to_c_array(tflite_model),
    )

    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(content, encoding="utf-8")
    print(f"  Saved header  → {header_path}")

    return tflite_model


# ── CLI ────────────────────────────────────────────────────────────────────────


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert a Keras model to LiteRT (.tflite) and an Arduino model.h header.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples
            --------
              python model_to_tflite.py saved_model/
              python model_to_tflite.py model.keras -o out/model.tflite --header out/model.h
              python model_to_tflite.py saved_model/ --quantize
        """),
    )
    parser.add_argument(
        "model_path",
        metavar="MODEL_PATH",
        help="Path to a SavedModel directory or a .keras / .h5 file.",
    )
    parser.add_argument(
        "-o", "--output",
        metavar="TFLITE_PATH",
        default=None,
        help="Output path for the .tflite file  [default: model.tflite next to MODEL_PATH]",
    )
    parser.add_argument(
        "--header",
        metavar="HEADER_PATH",
        default=None,
        help="Output path for the C header file  [default: model.h next to the .tflite file]",
    )
    parser.add_argument(
        "--quantize",
        action="store_true",
        help=(
            "Apply post-training INT8 quantisation.  "
            "Requires a representative_dataset; when used from the CLI a small "
            "random dataset is generated automatically (for shape inference only — "
            "accuracy calibration requires real data)."
        ),
    )
    parser.add_argument(
        "--select-ops",
        action="store_true",
        dest="select_ops",
        help=(
            "Enable SELECT_TF_OPS to handle ops without a native TFLite builtin "
            "(e.g. Keras LSTM with dynamic tensor lists).  "
            "WARNING: the resulting model is NOT compatible with TFLite Micro / Arduino.  "
            "For Arduino targets retrain with LSTM(unroll=True) instead."
        ),
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = _parse_args(argv)

    import numpy as np
    import tensorflow as tf

    model_path = Path(args.model_path)
    if not model_path.exists():
        print(f"ERROR: model path not found: {model_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Loading model from {model_path} …")
    model = tf.keras.models.load_model(str(model_path))
    model.summary()

    # Resolve output paths
    tflite_path = Path(args.output) if args.output else model_path.parent / "model.tflite"
    header_path = Path(args.header) if args.header else tflite_path.with_suffix(".h")

    # Build a dummy representative dataset from the model's input shape when
    # --quantize is requested from the CLI (no real calibration data available).
    representative_dataset = None
    if args.quantize:
        input_shape = model.input_shape  # e.g. (None, SEQ_LEN, NUM_FEATURES)
        concrete_shape = (1,) + tuple(input_shape[1:])
        print(
            f"  WARNING: using random data for INT8 calibration "
            f"(shape {concrete_shape}).  For accurate quantisation pass real "
            "representative data via the Python API.",
            file=sys.stderr,
        )

        def representative_dataset():
            for _ in range(100):
                yield [np.random.rand(*concrete_shape).astype(np.float32)]

    convert(
        model,
        tflite_path=tflite_path,
        header_path=header_path,
        quantize=args.quantize,
        representative_dataset=representative_dataset,
        select_ops=args.select_ops,
    )


if __name__ == "__main__":
    main()
