/**
 * Training data statistics for feature standardisation.
 *
 * Auto-generated by csv_to_statistics_h.py
 * Timestamp  : 2026-03-01 19:50 UTC
 * Source     : train_data.csv
 * Mode       : by-temp-profile (column 'plate_temperature', profile: 320 100 100 100 200 200 200 320 320 320)
 *
 * z-score normalisation applied per heater step:
 *
 *   z = (x - FEATURE_MEAN[step][i]) / FEATURE_STD[step][i]
 *
 * Features where FEATURE_STD[step][i] == 0.0 are passed through unchanged.
 * STATS_SEQ_LEN == 1 for forced-mode (single-step) models.
 *
 * Feature order — must match the order used when training the model:
 *   [0]  gas_resistance           ()
 *   [1]  gas_resistance_diff      ()
 */

#ifndef STATISTICS_H
#define STATISTICS_H

constexpr int STATS_SEQ_LEN = 10;

/* Per-step, per-feature mean  [heater_step][feature_index] */
const float FEATURE_MEAN[10][2] = {
    /* [320 °C] */
    {
        57904.2f,   // gas_resistance ()
        -30477.7f  // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        3.21115e+06f,  // gas_resistance ()
        910572.0f     // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        3.21115e+06f,  // gas_resistance ()
        910572.0f     // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        3.21115e+06f,  // gas_resistance ()
        910572.0f     // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        201768.0f,   // gas_resistance ()
        -871010.0f  // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        201768.0f,   // gas_resistance ()
        -871010.0f  // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        201768.0f,   // gas_resistance ()
        -871010.0f  // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        57904.2f,   // gas_resistance ()
        -30477.7f  // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        57904.2f,   // gas_resistance ()
        -30477.7f  // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        57904.2f,   // gas_resistance ()
        -30477.7f  // gas_resistance_diff ()
    }
};

/* Per-step, per-feature std   [heater_step][feature_index]  (0.0 = pass-through) */
const float FEATURE_STD[10][2] = {
    /* [320 °C] */
    {
        21103.2f,  // gas_resistance ()
        74237.5f  // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        1.98042e+06f,  // gas_resistance ()
        2.31593e+06f  // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        1.98042e+06f,  // gas_resistance ()
        2.31593e+06f  // gas_resistance_diff ()
    },
    /* [100 °C] */
    {
        1.98042e+06f,  // gas_resistance ()
        2.31593e+06f  // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        111680.0f,     // gas_resistance ()
        1.52046e+06f  // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        111680.0f,     // gas_resistance ()
        1.52046e+06f  // gas_resistance_diff ()
    },
    /* [200 °C] */
    {
        111680.0f,     // gas_resistance ()
        1.52046e+06f  // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        21103.2f,  // gas_resistance ()
        74237.5f  // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        21103.2f,  // gas_resistance ()
        74237.5f  // gas_resistance_diff ()
    },
    /* [320 °C] */
    {
        21103.2f,  // gas_resistance ()
        74237.5f  // gas_resistance_diff ()
    }
};

#endif /* STATISTICS_H */
